### PR TITLE
Changes to include IBM SSP CM, Engine, PS and SEAS charts to OCP Developer Catalog

### PR DESCRIPTION
**Pull request by durgesh-singh2**
The PR is for v1.1.3 release of our product offerings IBM Sterling Secure Proxy and Sterling External Authentication Server. This will be tgz only delivery. So please review it.

### CODE REVIEW

**Comment by durgesh-singh2** [comment]
Hi @pedjak @sbose78 request you or someone from your team to review this PR.

**Comment by dperaza4dustbit** [comment]
Thanks for you submission. Since the lunch of our helm certification program all chart should now be submitted to https://charts.openshift.io/. IBM is already a partner so I suggest to contact Nancy Heinz. She can guide you on how to submit the charts to be certified. If you determine that you are not ready for certification you can also send these charts through the community path described in the documentation: https://github.com/openshift-helm-charts/charts/tree/main/docs. Feel free to reach out if you have any questions.

**Comment by durgesh-singh2** [comment]
@dperaza4dustbit
I think this https://charts.openshift.io repo is used for OCP 4.8 and currently we are supporting OCP 4.6 for our helm charts. 
Also when I describe Helm Repository resource for 4.6 it's pointing to https://github.com/redhat-developer/redhat-helm-charts repo. Below information for the same: 

$ **oc get HelmChartRepository**
NAME               AGE
redhat-helm-repo   180d

$ **oc describe HelmChartRepository redhat-helm-repo**
Name:         redhat-helm-repo
Namespace:
Labels:       <none>
Annotations:  release.openshift.io/create-only: true
API Version:  helm.openshift.io/v1beta1
Kind:         HelmChartRepository
Metadata:
  Creation Timestamp:  2021-03-03T02:01:30Z
  Generation:          1
  Managed Fields:
    API Version:  helm.openshift.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:release.openshift.io/create-only:
      f:spec:
        .:
        f:connectionConfig:
          .:
          f:url:
        f:name:
    Manager:         cluster-version-operator
    Operation:       Update
    Time:            2021-03-03T02:01:30Z
  Resource Version:  48458457
  Self Link:         /apis/helm.openshift.io/v1beta1/helmchartrepositories/redhat-helm-repo
  UID:               2c10a767-7b45-46e0-859e-f0d0c897a1dd
Spec:
  Connection Config:
    URL:  **https://redhat-developer.github.io/redhat-helm-charts**
  Name:   Red Hat Helm Charts
Events:   <none>

@morstad 
FYI

**Comment by morstad** [comment]
@dperaza4dustbit As long as OCP 4.6/4.7 are supported we need to be able to update this repo - it is default OOB in those clusters.

**Comment by dperaza4dustbit** [comment]
@morstad and @durgesh-singh2 is anything keeping you from adding new repo to 4.6: 
oc apply -f https://charts.openshift.io/openshift-charts-repo.yaml
If you have that option I rather you send these charts as PRs to new repo: https://github.com/openshift-helm-charts/charts
Use the community path for that if you are not ready for certification.

**Comment by morstad** [comment]
@dperaza4dustbit OCP 4.6/4.7 clusters have the redhat-helm-charts repo in their clusters OOB - need to be able to continue to deliver updates to these customers automatically through this repo.

**Comment by dperaza4dustbit** [comment]
Understand @morstad looks like adding new repo is not an option.

**Comment by durgesh-singh2** [comment]
@dperaza4dustbit @morstad has also confirmed redhat-helm-charts is default repo for OCP 4.6/4.7. So can you please merge these changes now.

**Pull request merged**
