### PR TITLE
adding ability to use DockerImage output to push to an external registry

### PR DESCRIPTION
**Pull request by deweya**
Adds ability to push to an external registry. Users can now push to the internal registry (default, using ImageStreamTag output) or to an external registry (using DockerImage output)

Related issue: #41

### CODE REVIEW

**Review by sabre1041 — APPROVED** [review]
LGTM. Only potential enhancement would be to the README where there is a section on how to create a pull secret for secured repositories that this same process can be used for the push secret.

**Comment by sbose78** [comment]
Looks good, 

> LGTM. Only potential enhancement would be to the README where there is a section on how to create a pull secret for secured repositories that this same process can be used for the push secret.

+1

**Comment by deweya** [comment]
Updated the readme to include a note about the push secret

**Review by sabre1041 — APPROVED** [review]
LGTM

**Review by sbose78 — APPROVED** [review]

**Pull request merged**
