### PR TITLE
Changes to include IBM B2B and SFG charts to Developer Catalog

### PR DESCRIPTION
**Pull request by nikeshmi**
Changes to add IBM Sterling B2B Integrator and File Gateway charts to OCP Developer Catalog

### CODE REVIEW

**Comment by nikeshmi** [comment]
hi team, request to assign a reviewer to this PR?

**Comment by nikeshmi** [comment]
Hi @pedjak @sbose78   The PR is for v2.0.0 release of our product offerings IBM Sterling B2B Integrator and Sterling File Gateway. This will be tgz only delivery so I have removed the charts from stable/. Request you or someone from your team to please review it on priority.

Thanks,
Nikesh

**Comment by nikeshmi** [comment]
thank you @pedjak. had just one query - given the chart name ibm-b2bi-prod, the product name on the developer catalog is appearing as "Ibm B 2 Bi Prod" - Can we do something about the blank spaces in "B 2 Bi"?

**Comment by pedjak** [comment]
@rohitkrai03 can you help?

**Comment by nikeshmi** [comment]
@pedjak @rohitkrai03 any updates on this?

**Comment by rohitkrai03** [comment]
@nikeshmi Yes, we've added a fix in the UI to make sure the title doesn't split unexpectedly.

**Comment by nikeshmi** [comment]
@rohitkrai03 cool. thanks a lot for the update. What OCP version will carry that fix?

**Comment by nikeshmi** [comment]
Also had a quick query - while trying to install helm charts from the developer catalog on one of our on-prem environments it throws up this error "_Failed to install helm chart: could not get apiVersions from Kubernetes: unable to retrieve the complete list of server APIs: metering.ibm.com/v1: the server is currently unable to handle the request, webhook.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request_".  What are we missing here?

**Pull request merged**
