### PR TITLE
Add chart for EAP 7.4

### PR DESCRIPTION
**Pull request by jmesnil**
Signed-off-by: Jeff Mesnil <jmesnil@redhat.com>

### CODE REVIEW

**Comment by jmesnil** [comment]
mmhm afaict, the failure in the GH action is not related to the PR commit but to the setup of the action...

**Comment by dperaza4dustbit** [comment]
@jmesnil we are sunsetting this repo. Can you send your new chart to our new repo https://charts.openshift.io/

**Comment by dperaza4dustbit** [comment]
send the owners file in an initial PR: https://github.com/openshift-helm-charts/charts/tree/main/docs#preparation

If your chart is for a Red Hat product use the redhat path: https://github.com/openshift-helm-charts/charts/tree/main/charts/redhat/redhat

If your chart is an unsupported project use the community path: https://github.com/openshift-helm-charts/charts/tree/main/charts/community/redhat

**Comment by jmesnil** [comment]
@dperaza4dustbit thanks for the info, I've started the process to release EAP Helm charts with https://github.com/openshift-helm-charts/charts/pull/315

**Pull request closed without merging**
