### PR TITLE
Add a Vert.x Helm chart

### PR DESCRIPTION
**Pull request by jponge**
- Add a Vert.x helm chart for OpenShift
- Vert.x chart package and index update

### CODE REVIEW

**Comment by dperaza4dustbit** [comment]
@jponge thanks for your submission. Are you aware of this https://github.com/openshift-helm-charts/charts? Starting with OCP 4.8 this repository is the default one on OpenShift, consider submitting to that flow instead

**Comment by jponge** [comment]
Thanks @dperaza4dustbit 

Where are the charts sources maintained in that repository? I see tarballs (e.g. https://github.com/openshift-helm-charts/charts/blob/main/charts/redhat/redhat/quarkus/0.0.3/quarkus-0.0.3.tgz) but not the corresponding source.

**Comment by dperaza4dustbit** [comment]
@jponge The repo is not really a source repository, although you can share the source as part of the certification submission process. Every new version will basically be a new version folder that needs to be create. These charts are maintained elsewhere for source control and review. Most of them are maintained right on the project repo under a chart directory.

**Pull request closed without merging**
