### PR TITLE
Remove markdown in Chart.yaml

### PR DESCRIPTION
**Pull request by ambiknai**

### CODE REVIEW

**Comment by morstad** [comment]
@pedjak I am not seeing this change reflected in clusters - still seeing the incorrect markdown information : 
image

Can you check as to why?

**Comment by pedjak** [comment]
@morstad the markdown syntax was removed only in `Chart.yaml`, but `index.yaml` needs to be regenerated as well because the description is copied there as well. The PR did not contain these changes. Please create another PR with `index.yaml` changes.

**Comment by ambiknai** [comment]
> @morstad the markdown syntax was removed only in `Chart.yaml`, but `index.yaml` needs to be regenerated as well because the description is copied there as well. The PR did not contain these changes. Please create another PR with `index.yaml` changes.

Sure will create new PR for index.yaml changes. My understanding was index.yaml  needs to be generated only for first time onboarding PR.

**Comment by morstad** [comment]
@pedjak Of course, sorry should have caught that.  Thank you.

**Pull request merged**
