### PR TITLE
Adding IBM Sterling Order Management System v10 Charts

### PR DESCRIPTION
**Pull request by lokesh-murthy**

### CODE REVIEW

**Comment by sbose78** [comment]
Could you please add details/screenshots of testing that was done, with and without the console? 
:)

**Comment by vbashyamus** [comment]
Screen Shot 2020-04-14 at 6 31 18 PM
Screen Shot 2020-04-14 at 6 24 29 PM
Screen Shot 2020-04-14 at 6 24 08 PM
Screen Shot 2020-04-14 at 6 22 59 PM

**Comment by lokesh-murthy** [comment]
@pedjak, I have pushed the chart files into alpha folder.

**Comment by sbose78** [comment]
If the chart/product is released/`stable`, we should have it in `stable`, I would recommend.

**Comment by sbose78** [comment]
The screenshots look good. Thank you!

**Comment by lokesh-murthy** [comment]
@pedjak , I have resolved the merge conflicts and updated the PR.

**Pull request merged**
