### PR TITLE
IBM CPQ 4.0.0

### PR DESCRIPTION
**Pull request by nvaibhav**

### CODE REVIEW

**Comment by nvaibhav** [comment]
This is IBM CPQ release for chart 4.0.0 and Product version 10.0.0.12.
Please merge ASAP to complete our release.
Thanks

**Comment by sbose78** [comment]
Sure!

**Comment by sbose78** [comment]
May I have a description/declaration on what's been validated with this?

**Comment by nvaibhav** [comment]
IBM CPQ is a software product , packaging FixPack 12 with this release. 
This PR contains a new 4.0.0 tgz added representing FP12.
Also we have removed our oldest release 2.0.0.

After you approve this this would be available for our customers in Dev Catalog.
Ref to previous PR - https://github.com/redhat-developer/redhat-helm-charts/pull/26

Please expedite.
Thanks

**Pull request merged**
