### PR TITLE
Order Management Form-based Values Testing

### PR DESCRIPTION
**Pull request by ntinvo**
Testing new OCP 4.6 features for Order Management helm chart changes. Added values.schema.json for form-based values charts with schema. 
https://issues.redhat.com/browse/ODC-2993 - Form-based values for charts with schema

### CODE REVIEW

**Comment by sbose78** [comment]
Could you update th PR description with a message on why this change is being made?

**Comment by sbose78** [comment]
Did you intend to put them in "alpha"? Or do you think they should be in "stable"?

**Comment by ntinvo** [comment]
@sbose78  yes, the chart is not stable so I did intend to put it in the _alpha_ dir for testing the new form-based values charts.

**Comment by ntinvo** [comment]
@sbose78 do I need to do anything else to get this merged? Thank you!

**Comment by sbose78** [comment]
We are reviewing it, let me know if it's urgent or can wait a day?

**Comment by ntinvo** [comment]
It can wait a day! No worries. Thank you!

**Pull request closed without merging**
