### PR TITLE
IBM SSP CM, Engine, PS and SEAS charts v1.2.1 and v1.2.2 - 6030 iFx01(log4j 2.16.0) and iFix01plus(log4j 2.17.1) update

### PR DESCRIPTION
**Pull request by durgesh-singh2**
The PR is for v1.2.1 and v1.2.2 release of our product offerings IBM Sterling Secure Proxy and Sterling External Authentication Server. This will be tgz only delivery.
Currently we are supporting OCP 4.6 for our helm charts.
So please review it.

### CODE REVIEW

**Comment by durgesh-singh2** [comment]
Hi @dperaza4dustbit, Request you or someone from your team to review this PR.

**Comment by durgesh-singh2** [comment]
@dperaza4dustbit , @morstad : Any update on this

**Comment by durgesh-singh2** [comment]
Hi, @dperaza4dustbit @morstad  Can you please review this as it's pending since 7 days.

**Review by dperaza4dustbit — APPROVED** [review]
lgtm, for 4.8 and up summit to https://github.com/openshift-helm-charts/charts

**Pull request merged**
