### PR TITLE
OMS charts 6.0.0

### PR DESCRIPTION
**Pull request by ntinvo**
- added oms charts 6.0.0
- add ability to reuse existing PVC
- tls certs

### CODE REVIEW

**Comment by ntinvo** [comment]
@sbose78 can you review and merge the PR? 
We released our IBM charts today, I would like to have the charts available in Redhat as well.
Thank you,
Tin

**Comment by pedjak** [comment]
please resolve conflict.

**Comment by ntinvo** [comment]
@pedjak I've resolved the conflicts, please merge! Thank you!

**Comment by ntinvo** [comment]
@pedjak please provide an update, is there anything else I need to do, if not please merge it. Thank you!

**Comment by ntinvo** [comment]
@morstad @pedjak I've just resolved the conflicts.

**Pull request merged**
