### PR TITLE
CPQ Product charts added v4.0.3

### PR DESCRIPTION
**Pull request by nvaibhav**
We have added tar ball for CPQ 4.0.3 to the /charts for on boarding to catalog.

### CODE REVIEW

**Comment by nvaibhav** [comment]
We have added CPQ product 4.0.3. 
Also 4.0.2 was the previous version which we have discarded, hence we 4.0.3 should be the version we will be on-boarding.
Please process this PR.

**Comment by nvaibhav** [comment]
@dperaza4dustbit 
We have published and want to on-board.
Please approve.

**Comment by nvaibhav** [comment]
@zonggen
Please approve.

**Review by dperaza4dustbit — APPROVED** [review]
lgtm, keep in mind this will not show on OCP 4.8 or older unless you manually add this repo. The default repo for 4.8 or older is openshift-helm-charts

**Pull request merged**
