### PR TITLE
updated ibm-cpq-prod-3.1.0.tgz and index yaml

### PR DESCRIPTION
**Pull request by nvaibhav**
This is our release for 3.1.0 for Product IBM CPQ. We don't want to publish charts in /stable for security reasons. 
Our previous release 2.0.0 was released on the same lines. 
Please attend this PR ASAP.

### CODE REVIEW

**Comment by nvaibhav** [comment]
Please expedite.

**Comment by morstad** [comment]
@pedjak

**Comment by sbose78** [comment]
Hi @nvaibhav ! Sorry, I understand this went in later than expected.
We'll propose a better process to ensure we get to take in changes on time, and seek feedback on it.

**Comment by nvaibhav** [comment]
Thank you for acknowledging and looking into it.

**Pull request merged**
