### PR TITLE
adding quarkus chart

### PR DESCRIPTION
**Pull request by deweya**
This is the Quarkus Helm chart used for building and deploying a Quarkus application (in either Native or JVM mode) that we have discussed on our Helm Runtimes calls.

### CODE REVIEW

**Comment by sabre1041** [comment]
@deweya Experiencing issues performing a native build

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.757 s
[INFO] Finished at: 2020-11-21T04:24:52Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project getting-started: Cannot create resource output directory: /build/target/classes -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
subprocess exited with status 1
subprocess exited with status 1
STEP 5: FROM registry.redhat.io/ubi8/ubi-minimal
STEP 6: WORKDIR /deployments/
Error shutting down storage: A layer is mounted: layer is in use by a container
error: build error: error building at STEP "RUN ./mvnw clean package -Pnative": exit status 1
```

**Comment by deweya** [comment]
@sabre1041 Do you have a link to the app you were trying to build?

**Comment by deweya** [comment]
I think I fixed it by adding "USER root" to the first stage

**Comment by sabre1041** [comment]
@deweya confirmed the enhancement has resolved the build issue.

Would you be able to add the ability to specify resources on a build? This is needed especially for native builds

**Comment by deweya** [comment]
@sabre1041 Updated to allow the user to set build resources.

Also, when thinking about things like kafka, mongodb, etc, the user's going to need to configure their datasource in application.properties. The problem is that the current implementation requires this to be provided in a plaintext values.yaml file (using `applicationProperties.properties`. Do you think we should add a `applicationProperties.secretName` or something similar to let users pass an OCP secret name containing an application.properties file with secrets like credentials?

**Review by sabre1041 — CHANGES_REQUESTED** [review]
LGTM

**Review by sabre1041 — APPROVED** [review]

**Review by pedjak — APPROVED** [review]

**Pull request merged**
